# -*- mode: python -*-

Import("env")

env.Library(
    target='tracing',
    source=[
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)

env.Library(
    target='operation_span',
    source=[
        'operation_span.cpp',
    ],
    LIBDEPS=[
        'tracing',
    ],
    LIBDEPS_PRIVATE=[
        '$BUILD_DIR/mongo/db/service_context',
    ]
)
