# -*- mode: python; -*-

Import('env')

env = env.Clone()

env = env.Clone()
env.InjectThirdParty(libraries=['opentracing-cpp'])
env.CppUnitTest(
    target='util_opentracing_test',
    source=[
        'opentracing_test.cpp'
    ],
    LIBDEPS=[
        '$BUILD_DIR/third_party/shim_opentracing_cpp',
    ]
)
