# -*- mode: python -*-

Import('env')

env = env.Clone()

env.Library(
    target='sdam',
    source=[
        'datatypes.cpp',
        'server_description.cpp',
        'topology_description.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/repl/optime',
        '$BUILD_DIR/mongo/util/clock_sources'
    ],
    LIBDEPS_PRIVATE=[
    ],
)

env.CppUnitTest(
    target='topology_test',
    source=['topology_test.cpp'],
    LIBDEPS=['sdam'],
)

env.CppUnitTest(
    target='server_description_test',
    source=['server_description_test.cpp'],
    LIBDEPS=['sdam'],
)
